AllCops:
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 256

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateName:
  Enabled: true
  NameWhitelist:
    - is_a?
    - have_you_updated_changelog?
    - is_changelog_format_correct?

inherit_from: .rubocop_todo.yml
