AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateName:
  Enabled: true
  AllowedMethods:
    - is_a?
    - have_you_updated_changelog?
    - is_changelog_format_correct?

inherit_from: .rubocop_todo.yml
require:
  - rubocop-rake
  - rubocop-rspec